name = "fewd-mock-api"
type = "javascript"
compatibility_date = "2022-10-18"
route=""
required_secrets=["REDIS_URL", "REDIS_TOKEN"]
# NOTE: top-level vars are not inherited/extended

[env.kowospace]
# get zone_id here: https://dash.cloudflare.com/overview
zone_id = "8d8480758f960a314adcd3ec9b2f8967"
# NOTE: for dns feature of shpp scripts, use "route", not "routes"
kv_namespaces = [
	{ binding = "KV", id = "b41a5517fdd74a79a97c85327bbccf08" }
]

route = "fewd-mock-api.kowo.space/*"
vars = {  }

[build]
command = "$deploymode && { npm install && npm run build; exit $? ; } || echo '...build disabled...'"
[build.upload]
format = "modules"
main = "./index.mjs"

[miniflare]
kv_persist = true
port = 6421
